### ISSUE TITLE
Port C Entire CI Recipes from CWR

### ISSUE THREAD

**Issue by hollowaykeanho** [ChewKeanHo/AutomataCI#10]
### Description

Since the Native CI is entirely in shell scripts, I have to port the existing job recipes here. Data source: https://github.com/hollowaykeanho/cwr

### Expected Behavior

Template can initiate a C workspace immediately.

### Current Behavior

To initiate C workspace, manual efforts are needed.

**Comment by corygalyna** [comment]
Stuck?

**Comment by hollowaykeanho** [comment]
Most complicated one... too many permutation to handle...
