### ISSUE TITLE
Add Notarize CI Job Recipe

### ISSUE THREAD

**Issue by corygalyna** [ChewKeanHo/AutomataCI#127]
### Description

Proprietary OSes like MacOS and Windows have cryptographic notarization steps to deal with the authenticity distributions across their platforms. Without the notarization, user can be very skeptical about using the compiled binary.

### Expected Behavior

`./ci.cmd Notarize` is available.

### Current Behavior

`./ci.cmd Notarize` is unavailable.

**Comment by hollowaykeanho** [comment]
Ah, beautiful sharp eyes! =) I missed this one out. Thanks. Accepted task.

**Comment by hollowaykeanho** [comment]
Released in https://github.com/ChewKeanHo/AutomataCI/releases/tag/v2.0.0
