### ISSUE TITLE
Add Rust's Cargo Package and Release Ecosystems

### ISSUE THREAD

**Issue by corygalyna** [ChewKeanHo/AutomataCI#135]
### Description

Since Rust is going to be supported, it's better to support cargo distribution natively.

### Expected Behavior

Rust cargo is supported natively.

### Current Behavior

Rust cargo is not supported.

**Comment by hollowaykeanho** [comment]
Accepted.

**Comment by hollowaykeanho** [comment]
Released in https://github.com/ChewKeanHo/AutomataCI/releases/tag/v2.0.0
