### ISSUE TITLE
Add DEPLOY Recipe (after Release)

### ISSUE THREAD

**Issue by corygalyna** [ChewKeanHo/AutomataCI#136]
### Description

There are situations where some folks will want deployment CI job to be made available after releases. Let's facilitate the function but we don't have to use it.

### Expected Behavior

Deploy CI job is available.

### Current Behavior

Deploy CI job is unavailable.

**Comment by hollowaykeanho** [comment]
Same thought. Accepted.

**Comment by hollowaykeanho** [comment]
Released in https://github.com/ChewKeanHo/AutomataCI/releases/tag/v2.0.0
