### ISSUE TITLE
Add MSI Packager Recipe

### ISSUE THREAD

**Issue by corygalyna** [ChewKeanHo/AutomataCI#138]
### Description

Documents:

1. https://wiki.gnome.org/msitools
2. https://wiki.gnome.org/msitools/HowTo/CreateMSI
3. https://wixtoolset.org/
4. https://formulae.brew.sh/formula/msitools

### Expected Behavior

MSI installer packager is available.

### Current Behavior

MSI installer packager is unavailable.

**Comment by hollowaykeanho** [comment]
`env` ci job implemented.

**Comment by corygalyna** [comment]
Hey, no progress since 4 weeks ago? Stuck?

**Comment by hollowaykeanho** [comment]
Good morning. Yeah.. Windows side (`.Net`) stuffs with Wix4 alongside some ZORALab's client's stuffs.

**Comment by hollowaykeanho** [comment]
Should be fine.

**Comment by hollowaykeanho** [comment]
Hard to progress on Windows side. GitHub Actions for Windows OS is having some weird glitches where a simple task requires an hour to run.

Issue was traced here: https://github.com/actions/runner-images/issues/7320

I will drop this feature and merge in whatever we have. Then, we move on to other features.

**Comment by corygalyna** [comment]
An hour?!

**Comment by corygalyna** [comment]
So close to completion. If only you have access to a local Windows OS.

**Comment by hollowaykeanho** [comment]
after careful considerations, it's better to mark this as completed since we did produce MSI packages from the Windows side. Anything else we will just raise as new issue as bug report.

**Comment by hollowaykeanho** [comment]
Released in https://github.com/ChewKeanHo/AutomataCI/releases/tag/v2.0.0
