### ISSUE TITLE
Parallelize Package CI Job 

### ISSUE THREAD

**Issue by corygalyna** [ChewKeanHo/AutomataCI#140]
### Description

At the moment, the package CI job is strictly one at a time. Since `srcRUST` had shown how to parallelize a run, we can proceed to upgrade it and execute the tasks in parallel whenever available.

### Expected Behavior

package CI job is executed in parallel.

### Current Behavior

package CI job is executed in series, one at a time.

**Comment by hollowaykeanho** [comment]
Accepted... pull in.

**Comment by hollowaykeanho** [comment]
Released in https://github.com/ChewKeanHo/AutomataCI/releases/tag/v2.0.0
