### ISSUE TITLE
Port DEB Entire CI Recipes

### ISSUE THREAD

**Issue by hollowaykeanho** [ChewKeanHo/AutomataCI#15]
### Description

Since I got Debian `deb` distribution ecosystem and its build specs, I should port it in so that the packaging and releasing processes are simply seamless.

### Expected Behavior

packing `.deb` for Debian-based system are seamless.

### Current Behavior

manual efforts are needed.

**Comment by JeanShuralyov** [comment]
Merging from ZORALab's Monteur?

**Comment by hollowaykeanho** [comment]
yeap.. working on it at the moment.

**Comment by hollowaykeanho** [comment]
Implemented for UNIX system. Windows is set to not supported as documented.
