### ISSUE TITLE
Apply Corrections to All POSIX Shell for compilance & PowerShell similarity

### ISSUE THREAD

**Issue by hollowaykeanho** [ChewKeanHo/AutomataCI#152]
### Description

Apparently, all the POSIX shell were using Bash and a `::` library tag is actually a BASH thing. Although both MacOS and Linux are not having issues if they're using bash as the default `sh` option, other inferior shell terminals like `dash` will fail.

Besides, using the older underscore Titlecase convention instead of `::` allows cleaner and closer naming convention with PowerShell, making things a lot easier to document and communicate.

Therefore, let's amend it.

- [x] `automataCI/services/archive/ar`
- [x] `automataCI/services/archive/tar`
- [x] `automataCI/services/archive/zip`
- [x] `automataCI/services/checksum/md5`
- [x] `automataCI/services/checksum/shasum`
- [x] `automataCI/services/compilers/angular`
- [x] `automataCI/services/compilers/changelog`
- [x] `automataCI/services/compilers/citation`
- [x] `automataCI/services/compilers/copyright`
- [x] `automataCI/services/compilers/c`
- [x] `automataCI/services/compilers/deb`
- [x] `automataCI/services/compilers/docker`
- [x] `automataCI/services/compilers/flatpak`
- [x] `automataCI/services/compilers/go`
- [x] `automataCI/services/compilers/ipk`
- [x] `automataCI/services/compilers/manual`
- [x] `automataCI/services/compilers/msi`
- [x] `automataCI/services/compilers/nim`
- [x] `automataCI/services/compilers/python`
- [x] `automataCI/services/compilers/rpm`
- [x] `automataCI/services/compilers/rust`
- [x] `automataCI/services/compress/gz`
- [x] `automataCI/services/compress/xz`
- [x] `automataCI/services/crypto/notary`
- [x] `automataCI/services/crypto/gpg`
- [x] `automataCI/services/crypto/random`
- [x] `automataCI/services/i18n`
- [x] `automataCI/services/io/disk`
- [x] `automataCI/services/io/fs`
- [x] `automataCI/services/io/net/http`
- [x] `automataCI/services/io/os`
- [x] `automataCI/services/io/strings`
- [x] `automataCI/services/io/sync`
- [x] `automataCI/services/io/time`
- [x] `automataCI/services/publishers/chocolatey`
- [x] `automataCI/services/publishers/createrepo`
- [x] `automataCI/services/publishers/dotnet`
- [x] `automataCI/services/publishers/homebrew`
- [x] `automataCI/services/publishers/microsoft`
- [x] `automataCI/services/publishers/reprepro`
- [x] `automataCI/services/versioners/git`

### Expected Behavior

All POSIX Shell use underscore Titlecase convention (e.g. `STRINGS_To_Lowercase`).

### Current Behavior

All POSIX Shell is using Bash specific colon convention (e.g. `STRINGS::to_lowercase`).

### Steps to Reproduce [COMPULSORY]

1. Just read any of the POSIX shell script in `automataCI/` directory.

**Comment by corygalyna** [comment]
Ouch. Hey, might as well support i18n. Let's do it.

**Comment by corygalyna** [comment]
Also expands to PowerShell as well. Make it a single correction effort.

**Comment by corygalyna** [comment]
Checking in...

**Comment by hollowaykeanho** [comment]
Ok.. I'm back.. all in for this.

**Comment by hollowaykeanho** [comment]
@corygalyna , big patch coming in for `i18n` component amendment.

**Comment by corygalyna** [comment]
Got it Staging!

**Comment by corygalyna** [comment]
How big is big?

**Comment by hollowaykeanho** [comment]
> How big is big?

Affects all jobs. It's `i18n`.

**Comment by hollowaykeanho** [comment]
i18n pushed in

**Comment by hollowaykeanho** [comment]
completed go compiler.

**Comment by hollowaykeanho** [comment]
comleted nim compiler.

**Comment by hollowaykeanho** [comment]
completed c compiler due to nim dependency.

**Comment by corygalyna** [comment]
Finally, this task can be marked done soon.

**Comment by hollowaykeanho** [comment]
Released in https://github.com/ChewKeanHo/AutomataCI/releases/tag/v2.0.0
