### ISSUE TITLE
Support i18n Multiple Languages

### ISSUE THREAD

**Issue by corygalyna** [ChewKeanHo/AutomataCI#153]
### Description

Since the next release is non-backward compatible, it's better to support `i18n` as well for AutomataCI as it's also non-backward compatible. Looking forward for this release. =)

- [x] Env CI Job
- [x] Purge CI Job
- [x] Clean CI Job
- [x] Setup CI Job
- [x] Prepare CI Job
- [x] Start CI Job
- [x] Test CI Job
- [x] Build CI Job
- [x] Materialize CI Job
- [x] Notarize CI Job
- [x] Package CI Job
- [x] Release CI Job
- [x] Deploy CI Job
- [x] Stop CI Job
- [x] srcRUST CI recipes
- [x] srcGO CI recipes
- [x] srcANGULAR CI recipes
- [x] srcC CI recipes
- [x] srcNIM CI recipes
- [x] srcPYTHON CI recipes
- [x] src CI recipes
- [x] AutomataCI specs
- [x] README.md
- [x] System language auto-detect

### Expected Behavior

AutomataCI can operate in multiple languages.

### Current Behavior

AutomataCI is operating as a single language.

**Comment by hollowaykeanho** [comment]
ok

**Comment by hollowaykeanho** [comment]
Blocked by #154 due to Microsoft's terminals' encoding glitches.

**Comment by hollowaykeanho** [comment]
workign alongside while waiting for Windows OS side of MSI implementations...

**Comment by MinXinS** [comment]
几时完成啊？这个工程蛮可靠的。

**Comment by hollowaykeanho** [comment]
Working on it. Next part will have a leap.

**Comment by hollowaykeanho** [comment]
`src/` fully supported.

**Comment by corygalyna** [comment]
finally, some progress. :smile:

**Comment by hollowaykeanho** [comment]
`srcRUST` completed. Moving to Python tech.

**Comment by corygalyna** [comment]
status?

**Comment by hollowaykeanho** [comment]
working on `srcPYTHON`... there is a unknown bug failing the CI at the moment.

**Comment by corygalyna** [comment]
ok got it. =)

**Comment by hollowaykeanho** [comment]
`srcPYTHON` is completed. Entering `srcGO`...

**Comment by hollowaykeanho** [comment]
added `System language auto-detect` feature so that people don't have to set the language forcefully inside `CONFIG.toml` unless it is required.

**Comment by hollowaykeanho** [comment]
`srcGO` and `System language auto-detect` implemented.

**Comment by hollowaykeanho** [comment]
switching to `srcNIM`...

**Comment by corygalyna** [comment]
Still in nim?

**Comment by hollowaykeanho** [comment]
yeah.. closing, moving to Angular today.

**Comment by hollowaykeanho** [comment]
`srcNIM` completed.

**Comment by hollowaykeanho** [comment]
`srcANGULAR` completed.

**Comment by hollowaykeanho** [comment]
entering last one: `srcC`.

**Comment by hollowaykeanho** [comment]
`srcC` completed.

**Comment by hollowaykeanho** [comment]
Released in https://github.com/ChewKeanHo/AutomataCI/releases/tag/v2.0.0
