### ISSUE TITLE
Port Docker (GitHub Packages) CI Recipe

### ISSUE THREAD

**Issue by hollowaykeanho** [ChewKeanHo/AutomataCI#17]
### Description

Since I have this recipe in the past, I should port it in. 

### Expected Behavior

Packaging and releasing docker to GitHub Packages is seamless.

### Current Behavior

Packaging and releasing docker to GitHub Packages requires manual efforts.

**Comment by corygalyna** [comment]
Woah, this is great!

**Comment by hollowaykeanho** [comment]
Yeap. Implemented.
