### ISSUE TITLE
Port RPM Entire CI Recipe

### ISSUE THREAD

**Issue by hollowaykeanho** [ChewKeanHo/AutomataCI#20]
### Description

Don't leave out Red Hat's ecosystem's `rpm` distributions.

### Expected Behavior

NativeCI can package valid GPG-signed RPM.

### Current Behavior

No possible.

**Comment by corygalyna** [comment]
New stuff?

**Comment by hollowaykeanho** [comment]
yeap. Implementing tomorrow.

**Comment by corygalyna** [comment]
Nice. Do you need me to fork the repo for the pull request action?

**Comment by hollowaykeanho** [comment]
sure.

**Comment by corygalyna** [comment]
Done: https://github.com/corygalyna/AutomataCI

**Comment by hollowaykeanho** [comment]
Implemented.
