### ISSUE TITLE
Finalize Marketing Materials for v2.0.0 Release

### ISSUE THREAD

**Issue by corygalyna** [ChewKeanHo/AutomataCI#245]
### Description

Nice! You're getting very close to releasing v2.0.0. Please finalize the marketing materials before releasing.

### Expected Behavior

Marketing materials are great and attract more usability.

### Current Behavior

Marketing material as it is.

**Comment by hollowaykeanho** [comment]
Done. Do you want to take a look? It's in your repo now.

**Comment by corygalyna** [comment]
15 mins.. looking at it now.

**Comment by hollowaykeanho** [comment]
thanks. All clear then.

**Comment by hollowaykeanho** [comment]
Released in https://github.com/ChewKeanHo/AutomataCI/releases/tag/v2.0.0
