### ISSUE TITLE
Add Baseline `src/` Directory Recipe

### ISSUE THREAD

**Issue by corygalyna** [ChewKeanHo/AutomataCI#90]
### Description

In case someone wants to use it outside of supported technologies.

### Expected Behavior

A default baseline `src/` directory is supported with empty .ci jobs for development.

### Current Behavior

`src/` is support missing. How can you forget? haha. Everyone can only use it for Python tech.

**Comment by hollowaykeanho** [comment]
Oops. yeah, I forgot. Will do in `v1.5.0`.

**Comment by hollowaykeanho** [comment]
Implemented.
